# Generated by Django 3.2.6 on 2021-08-11 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0002_auto_20210809_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок видео')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тэги')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='videos/previews/', verbose_name='Превью')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('video', models.FileField(upload_to='videos/videos/', verbose_name='Видео')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='channels.channel', verbose_name='Канал')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
