# Generated by Django 3.2.6 on 2021-08-11 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videodislike_videolike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodislike',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dislike', to='videos.video'),
        ),
        migrations.AlterField(
            model_name='videolike',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='videos.video'),
        ),
    ]
