# Generated by Django 3.2.6 on 2021-08-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videolike',
            name='video',
        ),
        migrations.DeleteModel(
            name='VideoDislike',
        ),
        migrations.DeleteModel(
            name='VideoLike',
        ),
    ]
