# Generated by Django 3.2.6 on 2021-08-16 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20210812_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-created',), 'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
    ]
