# Generated by Django 3.2.6 on 2021-08-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20210816_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок хэштега')),
                ('slug', models.SlugField(blank=True, max_length=170, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Хэштег',
                'verbose_name_plural': 'Хэштеги',
            },
        ),
        migrations.RemoveField(
            model_name='video',
            name='tags',
        ),
        migrations.AddField(
            model_name='video',
            name='hashtags_list',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Список хэштегов'),
        ),
        migrations.AddField(
            model_name='video',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos', to='videos.Hashtag', verbose_name='Хэштеги'),
        ),
    ]
