# Generated by Django 3.2.6 on 2021-08-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20210816_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='video',
            name='hashtags_list',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
