# Generated by Django 3.2.6 on 2021-08-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_auto_20210811_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='private',
            field=models.CharField(choices=[('private', 'Для себя'), ('public', 'Для всех'), ('link', 'По ссылке')], default='private', max_length=15, verbose_name='Конфиденциальность'),
        ),
    ]
