# Generated by Django 3.2.6 on 2021-08-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_alter_playlist_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
