# Generated by Django 3.2.6 on 2021-08-09 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название канала')),
                ('slug', models.SlugField(verbose_name='URL канала')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='channels/banners/', verbose_name='Баннер канала')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='channels/avatars/', verbose_name='Фото канала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('subscribers', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='channel', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Канал',
                'verbose_name_plural': 'Каналы',
            },
        ),
    ]
